config/routes.rb
# frozen_string_literal: true
GoodJob::Engine.routes.draw do
  root to: redirect(path: 'jobs')

  resources :jobs, only: %i[index show destroy] do
    collection do
      get :mass_update, to: redirect(path: 'jobs')
      put :mass_update
    end

    member do
      put :discard
      put :reschedule
      put :retry
    end
  end

  resources :batches, only: %i[index show]

  resources :cron_entries, only: %i[index show], param: :cron_key do
    member do
      post :enqueue
      put :enable
      put :disable
    end
  end

  resources :processes, only: %i[index]

  scope :frontend, controller: :frontends do
    get "modules/:name", action: :module, as: :frontend_module, constraints: { format: 'js' }
    get "static/:name", action: :static, as: :frontend_static, constraints: { format: %w[css js] }
  end
end

app/models/concerns/good_job/filterable.rb
# frozen_string_literal: true
module GoodJob
  # Shared methods for filtering Execution/Job records from the +good_jobs+ table.
  module Filterable
    extend ActiveSupport::Concern

    included do
      # Get records in display order with optional keyset pagination.
      # @!method display_all(after_scheduled_at: nil, after_id: nil)
      # @!scope class
      # @param after_scheduled_at [DateTime, String, nil]
      #   Display records scheduled after this time for keyset pagination
      # @param after_id [Numeric, String, nil]
      #   Display records after this ID for keyset pagination
      # @return [ActiveRecord::Relation]
      scope :display_all, (lambda do |after_scheduled_at: nil, after_id: nil|
        query = order(Arel.sql('COALESCE(scheduled_at, created_at) DESC, id DESC'))
        if after_scheduled_at.present? && after_id.present?
          query = query.where(Arel.sql('(COALESCE(scheduled_at, created_at), id) < (:after_scheduled_at, :after_id)'), after_scheduled_at: after_scheduled_at, after_id: after_id)
        elsif after_scheduled_at.present?
          query = query.where(Arel.sql('(COALESCE(scheduled_at, created_at)) < (:after_scheduled_at)'), after_scheduled_at: after_scheduled_at)
        end
        query
      end)

      # Search records by text query.
      # @!method search_text(query)
      # @!scope class
      # @param query [String]
      #   Search Query
      # @return [ActiveRecord::Relation]
      scope :search_text, (lambda do |query|
        query = query.to_s.strip
        next if query.blank?

        tsvector = "(to_tsvector('english', serialized_params) || to_tsvector('english', id::text) || to_tsvector('english', COALESCE(error, '')::text))"
        to_tsquery_function = database_supports_websearch_to_tsquery? ? 'websearch_to_tsquery' : 'plainto_tsquery'
        where("#{tsvector} @@ #{to_tsquery_function}(?)", query)
          .order(sanitize_sql_for_order([Arel.sql("ts_rank(#{tsvector}, #{to_tsquery_function}(?))"), query]) => 'DESC')
      end)
    end

    class_methods do
      def database_supports_websearch_to_tsquery?
        return @_database_supports_websearch_to_tsquery if defined?(@_database_supports_websearch_to_tsquery)

        @_database_supports_websearch_to_tsquery = connection.postgresql_version >= 110000
      end
    end
  end
end

app/models/concerns/good_job/reportable.rb
# frozen_string_literal: true
module GoodJob
  module Reportable
    # There are 3 buckets of non-overlapping statuses:
    #   1. The job will be executed
    #     - queued: The job will execute immediately when an execution thread becomes available.
    #     - scheduled: The job is scheduled to execute in the future.
    #     - retried: The job previously errored on execution and will be re-executed in the future.
    #   2. The job is being executed
    #     - running: the job is actively being executed by an execution thread
    #   3. The job has finished
    #     - succeeded: The job executed successfully
    #     - discarded: The job previously errored on execution and will not be re-executed in the future.
    #
    # @return [Symbol]
    def status
      if finished_at.present?
        if error.present? && retried_good_job_id.present?
          :retried
        elsif error.present? && retried_good_job_id.nil?
          :discarded
        else
          :succeeded
        end
      elsif (scheduled_at || created_at) > DateTime.current
        if serialized_params.fetch('executions', 0) > 1
          :retried
        else
          :scheduled
        end
      elsif running?
        :running
      else
        :queued
      end
    end

    # The last relevant timestamp for this execution
    def last_status_at
      finished_at || performed_at || scheduled_at || created_at
    end
  end
end

app/models/good_job/active_job_job.rb
# frozen_string_literal: true
module GoodJob
  # @deprecated Use {GoodJob::Job} instead.
  class ActiveJobJob < Execution
    after_initialize do |_job|
      ActiveSupport::Deprecation.warn(
        "The `GoodJob::ActiveJobJob` class name is deprecated. Replace with `GoodJob::Job`."
      )
    end
  end
end

app/models/good_job/base_record.rb
# frozen_string_literal: true
module GoodJob
  # Base ActiveRecord class that all GoodJob models inherit from.
  # Parent class can be configured with +GoodJob.active_record_parent_class+.
  # @!parse
  #   class BaseRecord < ActiveRecord::Base; end
  class BaseRecord < Object.const_get(GoodJob.active_record_parent_class)
    self.abstract_class = true

    def self.migration_pending_warning!
      ActiveSupport::Deprecation.warn(<<~DEPRECATION)
        GoodJob has pending database migrations. To create the migration files, run:
            rails generate good_job:update
        To apply the migration files, run:
            rails db:migrate
      DEPRECATION
      nil
    end

    # Checks for whether the schema is up to date.
    # Can be overriden by child class.
    # @return [Boolean]
    def self.migrated?
      return true if connection.table_exists?(table_name)

      migration_pending_warning!
      false
    end
  end
end

app/models/good_job/execution_result.rb
# frozen_string_literal: true
module GoodJob
  # Stores the results of job execution
  class ExecutionResult
    # @return [Object, nil]
    attr_reader :value
    # @return [Exception, nil]
    attr_reader :handled_error
    # @return [Exception, nil]
    attr_reader :unhandled_error
    # @return [Exception, nil]
    attr_reader :retried
    alias retried? retried

    # @param value [Object, nil]
    # @param handled_error [Exception, nil]
    # @param unhandled_error [Exception, nil]
    def initialize(value:, handled_error: nil, unhandled_error: nil, retried: false)
      @value = value
      @handled_error = handled_error
      @unhandled_error = unhandled_error
      @retried = retried
    end
  end
end

app/controllers/good_job/application_controller.rb
# frozen_string_literal: true
module GoodJob
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    around_action :switch_locale

    content_security_policy do |policy|
      policy.default_src(:none) if policy.default_src(*policy.default_src).blank?
      policy.connect_src(:self) if policy.connect_src(*policy.connect_src).blank?
      policy.base_uri(:none) if policy.base_uri(*policy.base_uri).blank?
      policy.font_src(:self) if policy.font_src(*policy.font_src).blank?
      policy.img_src(:self, :data) if policy.img_src(*policy.img_src).blank?
      policy.object_src(:none) if policy.object_src(*policy.object_src).blank?
      policy.script_src(:self) if policy.script_src(*policy.script_src).blank?
      policy.style_src(:self) if policy.style_src(*policy.style_src).blank?
      policy.form_action(:self) if policy.form_action(*policy.form_action).blank?
      policy.frame_ancestors(:none) if policy.frame_ancestors(*policy.frame_ancestors).blank?
    end

    before_action do
      next if request.content_security_policy_nonce_generator

      request.content_security_policy_nonce_generator = ->(_request) { SecureRandom.base64(16) }
    end

    private

    def default_url_options(options = {})
      { locale: I18n.locale }.merge(options)
    end

    def switch_locale(&action)
      I18n.with_locale(current_locale, &action)
    end

    def current_locale
      if params[:locale]
        params[:locale]
      elsif good_job_available_locales.exclude?(I18n.default_locale) && I18n.available_locales.include?(:en)
        :en
      else
        I18n.default_locale
      end
    end

    def good_job_available_locales
      @_good_job_available_locales ||= GoodJob::Engine.root.join("config/locales").glob("*.yml").map { |path| File.basename(path, ".yml").to_sym }.uniq
    end
  end
end

app/controllers/good_job/batches_controller.rb
# frozen_string_literal: true
module GoodJob
  class BatchesController < GoodJob::ApplicationController
    def index
      @filter = BatchesFilter.new(params)
    end

    def show
      @batch = GoodJob::BatchRecord.find(params[:id])
    end
  end
end

app/controllers/good_job/cron_entries_controller.rb
# frozen_string_literal: true
module GoodJob
  class CronEntriesController < GoodJob::ApplicationController
    before_action :check_settings_migration!, only: [:enable, :disable]

    def index
      @cron_entries = CronEntry.all
    end

    def show
      @cron_entry = CronEntry.find(params[:cron_key])
      @jobs_filter = JobsFilter.new(params, @cron_entry.jobs)
    end

    def enqueue
      @cron_entry = CronEntry.find(params[:cron_key])
      @cron_entry.enqueue(Time.current)
      redirect_back(fallback_location: cron_entries_path, notice: "Cron entry has been enqueued.")
    end

    def enable
      @cron_entry = CronEntry.find(params[:cron_key])
      @cron_entry.enable
      redirect_back(fallback_location: cron_entries_path, notice: "Cron entry has been enabled.")
    end

    def disable
      @cron_entry = CronEntry.find(params[:cron_key])
      @cron_entry.disable
      redirect_back(fallback_location: cron_entries_path, notice: "Cron entry has been disabled.")
    end

    private

    def check_settings_migration!
      redirect_back(fallback_location: cron_entries_path, alert: "Requires pending GoodJob database migration.") unless GoodJob::Setting.migrated?
    end
  end
end

app/controllers/good_job/frontends_controller.rb
# frozen_string_literal: true
module GoodJob
  class FrontendsController < ActionController::Base # rubocop:disable Rails/ApplicationController
    skip_after_action :verify_same_origin_request, raise: false

    STATIC_ASSETS = {
      css: {
        bootstrap: GoodJob::Engine.root.join("app", "frontend", "good_job", "vendor", "bootstrap", "bootstrap.min.css"),
        style: GoodJob::Engine.root.join("app", "frontend", "good_job", "style.css"),
      },
      js: {
        bootstrap: GoodJob::Engine.root.join("app", "frontend", "good_job", "vendor", "bootstrap", "bootstrap.bundle.min.js"),
        chartjs: GoodJob::Engine.root.join("app", "frontend", "good_job", "vendor", "chartjs", "chart.min.js"),
        es_module_shims: GoodJob::Engine.root.join("app", "frontend", "good_job", "vendor", "es_module_shims.js"),
        rails_ujs: GoodJob::Engine.root.join("app", "frontend", "good_job", "vendor", "rails_ujs.js"),
      },
    }.freeze

    MODULE_OVERRIDES = {
      application: GoodJob::Engine.root.join("app", "frontend", "good_job", "application.js"),
      stimulus: GoodJob::Engine.root.join("app", "frontend", "good_job", "vendor", "stimulus.js"),
    }.freeze

    def self.js_modules
      @_js_modules ||= GoodJob::Engine.root.join("app", "frontend", "good_job", "modules").children.select(&:file?).each_with_object({}) do |file, modules|
        key = File.basename(file.basename.to_s, ".js").to_sym
        modules[key] = file
      end.merge(MODULE_OVERRIDES)
    end

    before_action do
      expires_in 1.year, public: true
    end

    def static
      render file: STATIC_ASSETS.dig(params[:format].to_sym, params[:name].to_sym) || raise(ActionController::RoutingError, 'Not Found')
    end

    def module
      raise(ActionController::RoutingError, 'Not Found') if params[:format] != "js"

      render file: self.class.js_modules[params[:name].to_sym] || raise(ActionController::RoutingError, 'Not Found')
    end
  end
end

app/controllers/good_job/jobs_controller.rb
# frozen_string_literal: true
module GoodJob
  class JobsController < GoodJob::ApplicationController
    DISCARD_MESSAGE = "Discarded through dashboard"

    ACTIONS = {
      discard: "discarded",
      reschedule: "rescheduled",
      retry: "retried",
      destroy: "destroyed",
    }.freeze

    rescue_from GoodJob::Job::AdapterNotGoodJobError,
                GoodJob::Job::ActionForStateMismatchError,
                with: :redirect_on_error

    def index
      @filter = JobsFilter.new(params)
    end

    def mass_update
      mass_action = params.fetch(:mass_action, "").to_sym
      raise ActionController::BadRequest, "#{mass_action} is not a valid mass action" unless mass_action.in?(ACTIONS.keys)

      jobs = if params[:all_job_ids]
               JobsFilter.new(params).filtered_query
             else
               job_ids = params.fetch(:job_ids, [])
               Job.where(active_job_id: job_ids)
             end

      processed_jobs = jobs.map do |job|
        case mass_action
        when :discard
          job.discard_job(DISCARD_MESSAGE)
        when :reschedule
          job.reschedule_job
        when :retry
          job.retry_job
        when :destroy
          job.destroy_job
        end

        job
      rescue GoodJob::Job::ActionForStateMismatchError
        nil
      end.compact

      notice = if processed_jobs.any?
                 "Successfully #{ACTIONS[mass_action]} #{processed_jobs.count} #{'job'.pluralize(processed_jobs.count)}"
               else
                 "No jobs were #{ACTIONS[mass_action]}"
               end

      redirect_back(fallback_location: jobs_path, notice: notice)
    end

    def show
      @job = Job.includes_advisory_locks.find(params[:id])
    end

    def discard
      @job = Job.find(params[:id])
      @job.discard_job(DISCARD_MESSAGE)
      redirect_back(fallback_location: jobs_path, notice: "Job has been discarded")
    end

    def reschedule
      @job = Job.find(params[:id])
      @job.reschedule_job
      redirect_back(fallback_location: jobs_path, notice: "Job has been rescheduled")
    end

    def retry
      @job = Job.find(params[:id])
      @job.retry_job
      redirect_back(fallback_location: jobs_path, notice: "Job has been retried")
    end

    def destroy
      @job = Job.find(params[:id])
      @job.destroy_job
      redirect_to jobs_path, notice: "Job has been destroyed"
    end

    private

    def redirect_on_error(exception)
      alert = case exception
              when GoodJob::Job::AdapterNotGoodJobError
                "ActiveJob Queue Adapter must be GoodJob."
              when GoodJob::Job::ActionForStateMismatchError
                "Job is not in an appropriate state for this action."
              else
                exception.to_s
              end
      redirect_back(fallback_location: jobs_path, alert: alert)
    end
  end
end

app/controllers/good_job/processes_controller.rb
# frozen_string_literal: true
module GoodJob
  class ProcessesController < GoodJob::ApplicationController
    def index
      @processes = GoodJob::Process.active.order(created_at: :desc)
    end
  end
end

app/helpers/good_job/application_helper.rb
# frozen_string_literal: true
module GoodJob
  module ApplicationHelper
    def format_duration(sec)
      return unless sec

      if sec < 1
        t 'good_job.duration.milliseconds', ms: (sec * 1000).floor
      elsif sec < 10
        t 'good_job.duration.less_than_10_seconds', sec: sec.floor
      elsif sec < 60
        t 'good_job.duration.seconds', sec: sec.floor
      elsif sec < 3600
        t 'good_job.duration.minutes', min: (sec / 60).floor, sec: (sec % 60).floor
      else
        t 'good_job.duration.hours', hour: (sec / 3600).floor, min: ((sec % 3600) / 60).floor
      end
    end

    def relative_time(timestamp, **options)
      options = options.reverse_merge({ scope: "good_job.datetime.distance_in_words" })
      text = timestamp.future? ? "in #{time_ago_in_words(timestamp, **options)}" : "#{time_ago_in_words(timestamp, **options)} ago"
      tag.time(text, datetime: timestamp, title: timestamp)
    end

    STATUS_ICONS = {
      discarded: "exclamation",
      succeeded: "check",
      queued: "dash_circle",
      retried: "arrow_clockwise",
      running: "play",
      scheduled: "clock",
    }.freeze

    STATUS_COLOR = {
      discarded: "danger",
      succeeded: "success",
      queued: "secondary",
      retried: "warning",
      running: "primary",
      scheduled: "secondary",
    }.freeze

    def status_badge(status)
      content_tag :span, status_icon(status, class: "text-white") + t(status, scope: 'good_job.status'),
                  class: "badge rounded-pill bg-#{STATUS_COLOR.fetch(status)} d-inline-flex gap-2 ps-1 pe-3 align-items-center"
    end

    def status_icon(status, **options)
      options[:class] ||= "text-#{STATUS_COLOR.fetch(status)}"
      icon = render_icon STATUS_ICONS.fetch(status)
      content_tag :span, icon, **options
    end

    def render_icon(name)
      # workaround to render svg icons without all of the log messages
      partial = lookup_context.find_template("good_job/shared/icons/#{name}", [], true)
      partial.render(self, {})
    end
  end
end

app/views/good_job/shared/_alert.erb
<div class="toast-container position-fixed p-3 start-50 translate-middle-x">
  <% if notice %>
    <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-body d-flex align-items-center gap-2">
        <%= render "good_job/shared/icons/check", class: "flex-shrink-0 text-success" %>
        <div class="flex-fill"><%= notice %></div>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
    </div>
  <% end %>
  <% if alert %>
    <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-body d-flex align-items-center gap-2">
        <%= render "good_job/shared/icons/exclamation", class: "flex-shrink-0 text-danger" %>
        <div class="flex-fill"><%= alert %></div>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
    </div>
  <% end %>
</div>

app/views/good_job/shared/_chart.erb
<div class="py-4" data-live-poll-region="chart">
  <div class="chart-wrapper container-fluid">
    <canvas class="chart" data-json="<%= chart_data.to_json %>"></canvas>
  </div>
</div>

app/views/good_job/shared/_filter.erb
<div data-live-poll-region id="filter" class="">
  <div class="">
    <div class="border-bottom mb-3">
      <h2 class="pt-3 pb-2"><%= title %></h2>
    </div>

    <%= form_with(url: "", method: :get, local: true, id: "filter_form", class: "") do |form| %>
      <%= hidden_field_tag :poll, params[:poll] %>
      <%= hidden_field_tag :state, params[:state] %>
      <%= hidden_field_tag :locale, params[:locale] if params[:locale] %>
      <div class="d-md-flex flex-row w-100">
        <div class="me-md-2 mb-2 mb-md-0">
          <%= label_tag "job_queue_filter", "Queue name", class: "visually-hidden" %>
          <select name="queue_name" id="job_queue_filter" class="form-select form-select-sm">
            <option value="" <%= "selected='selected'" if params[:queue_name].blank? %>>All queues</option>

            <% filter.queues.each do |name, count| %>
              <option value="<%= name.to_param %>" <%= "selected='selected'" if params[:queue_name] == name %>><%= name %> (<%= number_with_delimiter(count, t('good_job.number.format')) %>)</option>
            <% end %>
          </select>
        </div>

        <div class="me-md-2 mb-2 mb-md-0">
          <%= label_tag "job_class_filter", "Job name", class: "visually-hidden" %>
          <select name="job_class" id="job_class_filter" class="form-select form-select-sm">
            <option value="" <%= "selected='selected'" if params[:job_class].blank? %>>All jobs</option>

            <% filter.job_classes.each do |name, count| %>
              <option value="<%= name.to_param %>" <%= "selected='selected'" if params[:job_class] == name %>><%= name %> (<%= number_with_delimiter(count, t('good_job.number.format')) %>)</option>
            <% end %>
          </select>
        </div>

        <div class="me-md-2 mb-2 mb-md-0 flex-fill">
          <%= label_tag "query", "Search", class: "visually-hidden" %>
          <%= search_field_tag "query", params[:query], class: "form-control form-control-sm", placeholder: "Search by class, job id, job params, and error text." %>
        </div>

        <div class="d-flex flex-col align-items-end">
          <div>
            <%= form.submit "Search", name: nil, class: "btn btn-primary btn-sm" %>
            <%= link_to filter.to_params(job_class: nil, state: nil, queue_name: nil, query: nil), class: "btn btn-secondary btn-sm" do %>
              Clear
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

    <ul class="nav nav-tabs my-3">
      <li class="nav-item">
        <%= link_to "All", filter.to_params(state: nil), class: "nav-link #{"active" unless params[:state].present?}" %>
      </li>

      <% filter.states.each do |name, count| %>
        <li class="nav-item">
          <%= link_to filter.to_params(state: name), class: "nav-link #{"active" if params[:state] == name}" do %>
            <%= t(name, scope: 'good_job.status') %>
            <span class="badge bg-primary rounded-pill <%= "bg-secondary" if count == 0 %>"><%= number_with_delimiter(count, t('good_job.number.format')) %></span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>

  <%= javascript_tag nonce: true do %>
    document.addEventListener("DOMContentLoaded", () => {
      document.querySelectorAll("#job_class_filter, #job_queue_filter").forEach((filter) => {
        filter.addEventListener("change", () => {
          document.querySelector("#filter_form").submit();
        });
      })
    })
  <% end %>
</div>

app/views/good_job/shared/_footer.erb
<footer class="footer mt-auto py-3 bg-light border-top text-muted small" id="footer" data-live-poll-region="footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-6">
        <%= t(".last_update_html", time: Time.current.utc.iso8601) %>
      </div>

      <div class="col-6 text-end">
        <%= t(".wording") %>
      </div>
    </div>
  </div>
</footer>

app/views/good_job/shared/_navbar.erb
<nav class="navbar navbar-expand-lg navbar-light border-bottom bg-white sticky-top shadow-sm">
  <div class="container-fluid">
    <%= link_to t(".name"), root_path, class: "navbar-brand mb-0 h1" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to jobs_path, class: ["nav-link", ("active" if controller_name == 'jobs')] do %>
            <%= t(".jobs") %>
            <% jobs_count = GoodJob::Job.count %>
            <span class="badge bg-secondary rounded-pill"><%= number_to_human(jobs_count, **I18n.t("good_job.number.human.decimal_units")) %></span>
        <% end %>
        </li>
        <li class="nav-item">
          <%= link_to batches_path, class: ["nav-link", ("active" if controller_name == 'batches')] do %>
            <%= "Batches" %>
            <% batches_count = GoodJob::BatchRecord.migrated? ? GoodJob::BatchRecord.all.size : 0 %>
            <span class="badge bg-secondary rounded-pill"><%= number_to_human(batches_count, units: I18n.t("good_job.number.human.decimal_units.units"), precision: 3) %></span>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to cron_entries_path, class: ["nav-link", ("active" if controller_name == 'cron_entries')] do %>
            <%= t(".cron_schedules") %>
            <% cron_entries_count = GoodJob::CronEntry.all.size %>
            <span class="badge bg-secondary rounded-pill"><%= cron_entries_count %></span>
        <% end %>
        </li>
        <li class="nav-item">
          <%= link_to processes_path, class: ["nav-link", ("active" if controller_name == 'processes')] do %>
            <%= t(".processes") %>
            <% processes_count = GoodJob::Process.active.count %>
            <span class="badge bg-secondary rounded-pill <%= "bg-danger" if processes_count == 0 %>"><%= processes_count %></span>
          <% end %>
        </li>
      </ul>
      <div class="nav-item pe-2">
        <label>
          <%= check_box_tag "live_poll", params.fetch("poll", 30), params[:poll].present? %>
          <%= t(".live_poll") %>
        </label>
      </div>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" type="button" id="localeOptions" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= I18n.locale %>
          </a>

          <ul class="dropdown-menu" aria-labelledby="localeOptions">
            <% I18n.available_locales.reject { |locale| locale == I18n.locale }.each do |locale| %>
              <li><%= link_to locale, url_for(locale: locale), class: "dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>