config/routes.rb
# frozen_string_literal: true
GoodJob::Engine.routes.draw do
  root to: redirect(path: 'jobs')

  resources :jobs, only: %i[index show destroy] do
    collection do
      get :mass_update, to: redirect(path: 'jobs')
      put :mass_update
    end

    member do
      put :discard
      put :reschedule
      put :retry
    end
  end

  resources :batches, only: %i[index show]

  resources :cron_entries, only: %i[index show], param: :cron_key do
    member do
      post :enqueue
      put :enable
      put :disable
    end
  end

  resources :processes, only: %i[index]

  scope :frontend, controller: :frontends do
    get "modules/:name", action: :module, as: :frontend_module, constraints: { format: 'js' }
    get "static/:name", action: :static, as: :frontend_static, constraints: { format: %w[css js] }
  end
end

app/models/concerns/good_job/filterable.rb
# frozen_string_literal: true
module GoodJob
  # Shared methods for filtering Execution/Job records from the +good_jobs+ table.
  module Filterable
    extend ActiveSupport::Concern

    included do
      # Get records in display order with optional keyset pagination.
      # @!method display_all(after_scheduled_at: nil, after_id: nil)
      # @!scope class
      # @param after_scheduled_at [DateTime, String, nil]
      #   Display records scheduled after this time for keyset pagination
      # @param after_id [Numeric, String, nil]
      #   Display records after this ID for keyset pagination
      # @return [ActiveRecord::Relation]
      scope :display_all, (lambda do |after_scheduled_at: nil, after_id: nil|
        query = order(Arel.sql('COALESCE(scheduled_at, created_at) DESC, id DESC'))
        if after_scheduled_at.present? && after_id.present?
          query = query.where(Arel.sql('(COALESCE(scheduled_at, created_at), id) < (:after_scheduled_at, :after_id)'), after_scheduled_at: after_scheduled_at, after_id: after_id)
        elsif after_scheduled_at.present?
          query = query.where(Arel.sql('(COALESCE(scheduled_at, created_at)) < (:after_scheduled_at)'), after_scheduled_at: after_scheduled_at)
        end
        query
      end)

      # Search records by text query.
      # @!method search_text(query)
      # @!scope class
      # @param query [String]
      #   Search Query
      # @return [ActiveRecord::Relation]
      scope :search_text, (lambda do |query|
        query = query.to_s.strip
        next if query.blank?

        tsvector = "(to_tsvector('english', serialized_params) || to_tsvector('english', id::text) || to_tsvector('english', COALESCE(error, '')::text))"
        to_tsquery_function = database_supports_websearch_to_tsquery? ? 'websearch_to_tsquery' : 'plainto_tsquery'
        where("#{tsvector} @@ #{to_tsquery_function}(?)", query)
          .order(sanitize_sql_for_order([Arel.sql("ts_rank(#{tsvector}, #{to_tsquery_function}(?))"), query]) => 'DESC')
      end)
    end

    class_methods do
      def database_supports_websearch_to_tsquery?
        return @_database_supports_websearch_to_tsquery if defined?(@_database_supports_websearch_to_tsquery)

        @_database_supports_websearch_to_tsquery = connection.postgresql_version >= 110000
      end
    end
  end
end

app/models/concerns/good_job/reportable.rb
# frozen_string_literal: true
module GoodJob
  module Reportable
    # There are 3 buckets of non-overlapping statuses:
    #   1. The job will be executed
    #     - queued: The job will execute immediately when an execution thread becomes available.
    #     - scheduled: The job is scheduled to execute in the future.
    #     - retried: The job previously errored on execution and will be re-executed in the future.
    #   2. The job is being executed
    #     - running: the job is actively being executed by an execution thread
    #   3. The job has finished
    #     - succeeded: The job executed successfully
    #     - discarded: The job previously errored on execution and will not be re-executed in the future.
    #
    # @return [Symbol]
    def status
      if finished_at.present?
        if error.present? && retried_good_job_id.present?
          :retried
        elsif error.present? && retried_good_job_id.nil?
          :discarded
        else
          :succeeded
        end
      elsif (scheduled_at || created_at) > DateTime.current
        if serialized_params.fetch('executions', 0) > 1
          :retried
        else
          :scheduled
        end
      elsif running?
        :running
      else
        :queued
      end
    end

    # The last relevant timestamp for this execution
    def last_status_at
      finished_at || performed_at || scheduled_at || created_at
    end
  end
end

app/models/good_job/active_job_job.rb
# frozen_string_literal: true
module GoodJob
  # @deprecated Use {GoodJob::Job} instead.
  class ActiveJobJob < Execution
    after_initialize do |_job|
      ActiveSupport::Deprecation.warn(
        "The `GoodJob::ActiveJobJob` class name is deprecated. Replace with `GoodJob::Job`."
      )
    end
  end
end

app/models/good_job/base_record.rb
# frozen_string_literal: true
module GoodJob
  # Base ActiveRecord class that all GoodJob models inherit from.
  # Parent class can be configured with +GoodJob.active_record_parent_class+.
  # @!parse
  #   class BaseRecord < ActiveRecord::Base; end
  class BaseRecord < Object.const_get(GoodJob.active_record_parent_class)
    self.abstract_class = true

    def self.migration_pending_warning!
      ActiveSupport::Deprecation.warn(<<~DEPRECATION)
        GoodJob has pending database migrations. To create the migration files, run:
            rails generate good_job:update
        To apply the migration files, run:
            rails db:migrate
      DEPRECATION
      nil
    end

    # Checks for whether the schema is up to date.
    # Can be overriden by child class.
    # @return [Boolean]
    def self.migrated?
      return true if connection.table_exists?(table_name)

      migration_pending_warning!
      false
    end
  end
end

app/models/good_job/execution_result.rb
# frozen_string_literal: true
module GoodJob
  # Stores the results of job execution
  class ExecutionResult
    # @return [Object, nil]
    attr_reader :value
    # @return [Exception, nil]
    attr_reader :handled_error
    # @return [Exception, nil]
    attr_reader :unhandled_error
    # @return [Exception, nil]
    attr_reader :retried
    alias retried? retried

    # @param value [Object, nil]
    # @param handled_error [Exception, nil]
    # @param unhandled_error [Exception, nil]
    def initialize(value:, handled_error: nil, unhandled_error: nil, retried: false)
      @value = value
      @handled_error = handled_error
      @unhandled_error = unhandled_error
      @retried = retried
    end
  end
end

app/controllers/good_job/application_controller.rb
# frozen_string_literal: true
module GoodJob
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    around_action :switch_locale

    content_security_policy do |policy|
      policy.default_src(:none) if policy.default_src(*policy.default_src).blank?
      policy.connect_src(:self) if policy.connect_src(*policy.connect_src).blank?
      policy.base_uri(:none) if policy.base_uri(*policy.base_uri).blank?
      policy.font_src(:self) if policy.font_src(*policy.font_src).blank?
      policy.img_src(:self, :data) if policy.img_src(*policy.img_src).blank?
      policy.object_src(:none) if policy.object_src(*policy.object_src).blank?
      policy.script_src(:self) if policy.script_src(*policy.script_src).blank?
      policy.style_src(:self) if policy.style_src(*policy.style_src).blank?
      policy.form_action(:self) if policy.form_action(*policy.form_action).blank?
      policy.frame_ancestors(:none) if policy.frame_ancestors(*policy.frame_ancestors).blank?
    end

    before_action do
      next if request.content_security_policy_nonce_generator

      request.content_security_policy_nonce_generator = ->(_request) { SecureRandom.base64(16) }
    end

    private

    def default_url_options(options = {})
      { locale: I18n.locale }.merge(options)
    end

    def switch_locale(&action)
      I18n.with_locale(current_locale, &action)
    end

    def current_locale
      if params[:locale]
        params[:locale]
      elsif good_job_available_locales.exclude?(I18n.default_locale) && I18n.available_locales.include?(:en)
        :en
      else
        I18n.default_locale
      end
    end

    def good_job_available_locales
      @_good_job_available_locales ||= GoodJob::Engine.root.join("config/locales").glob("*.yml").map { |path| File.basename(path, ".yml").to_sym }.uniq
    end
  end
end

app/controllers/good_job/batches_controller.rb
# frozen_string_literal: true
module GoodJob
  class BatchesController < GoodJob::ApplicationController
    def index
      @filter = BatchesFilter.new(params)
    end

    def show
      @batch = GoodJob::BatchRecord.find(params[:id])
    end
  end
end

app/controllers/good_job/cron_entries_controller.rb
# frozen_string_literal: true
module GoodJob
  class CronEntriesController < GoodJob::ApplicationController
    before_action :check_settings_migration!, only: [:enable, :disable]

    def index
      @cron_entries = CronEntry.all
    end

    def show
      @cron_entry = CronEntry.find(params[:cron_key])
      @jobs_filter = JobsFilter.new(params, @cron_entry.jobs)
    end

    def enqueue
      @cron_entry = CronEntry.find(params[:cron_key])
      @cron_entry.enqueue(Time.current)
      redirect_back(fallback_location: cron_entries_path, notice: "Cron entry has been enqueued.")
    end

    def enable
      @cron_entry = CronEntry.find(params[:cron_key])
      @cron_entry.enable
      redirect_back(fallback_location: cron_entries_path, notice: "Cron entry has been enabled.")
    end

    def disable
      @cron_entry = CronEntry.find(params[:cron_key])
      @cron_entry.disable
      redirect_back(fallback_location: cron_entries_path, notice: "Cron entry has been disabled.")
    end

    private

    def check_settings_migration!
      redirect_back(fallback_location: cron_entries_path, alert: "Requires pending GoodJob database migration.") unless GoodJob::Setting.migrated?
    end
  end
end

app/controllers/good_job/frontends_controller.rb
# frozen_string_literal: true
module GoodJob
  class FrontendsController < ActionController::Base # rubocop:disable Rails/ApplicationController
    skip_after_action :verify_same_origin_request, raise: false

    STATIC_ASSETS = {
      css: {
        bootstrap: GoodJob::Engine.root.join("app", "frontend", "good_job", "vendor", "bootstrap", "bootstrap.min.css"),
        style: GoodJob::Engine.root.join("app", "frontend", "good_job", "style.css"),
      },
      js: {
        bootstrap: GoodJob::Engine.root.join("app", "frontend", "good_job", "vendor", "bootstrap", "bootstrap.bundle.min.js"),
        chartjs: GoodJob::Engine.root.join("app", "frontend", "good_job", "vendor", "chartjs", "chart.min.js"),
        es_module_shims: GoodJob::Engine.root.join("app", "frontend", "good_job", "vendor", "es_module_shims.js"),
        rails_ujs: GoodJob::Engine.root.join("app", "frontend", "good_job", "vendor", "rails_ujs.js"),
      },
    }.freeze

    MODULE_OVERRIDES = {
      application: GoodJob::Engine.root.join("app", "frontend", "good_job", "application.js"),
      stimulus: GoodJob::Engine.root.join("app", "frontend", "good_job", "vendor", "stimulus.js"),
    }.freeze

    def self.js_modules
      @_js_modules ||= GoodJob::Engine.root.join("app", "frontend", "good_job", "modules").children.select(&:file?).each_with_object({}) do |file, modules|
        key = File.basename(file.basename.to_s, ".js").to_sym
        modules[key] = file
      end.merge(MODULE_OVERRIDES)
    end

    before_action do
      expires_in 1.year, public: true
    end

    def static
      render file: STATIC_ASSETS.dig(params[:format].to_sym, params[:name].to_sym) || raise(ActionController::RoutingError, 'Not Found')
    end

    def module
      raise(ActionController::RoutingError, 'Not Found') if params[:format] != "js"

      render file: self.class.js_modules[params[:name].to_sym] || raise(ActionController::RoutingError, 'Not Found')
    end
  end
end

app/controllers/good_job/jobs_controller.rb
# frozen_string_literal: true
module GoodJob
  class JobsController < GoodJob::ApplicationController
    DISCARD_MESSAGE = "Discarded through dashboard"

    ACTIONS = {
      discard: "discarded",
      reschedule: "rescheduled",
      retry: "retried",
      destroy: "destroyed",
    }.freeze

    rescue_from GoodJob::Job::AdapterNotGoodJobError,
                GoodJob::Job::ActionForStateMismatchError,
                with: :redirect_on_error

    def index
      @filter = JobsFilter.new(params)
    end

    def mass_update
      mass_action = params.fetch(:mass_action, "").to_sym
      raise ActionController::BadRequest, "#{mass_action} is not a valid mass action" unless mass_action.in?(ACTIONS.keys)

      jobs = if params[:all_job_ids]
               JobsFilter.new(params).filtered_query
             else
               job_ids = params.fetch(:job_ids, [])
               Job.where(active_job_id: job_ids)
             end

      processed_jobs = jobs.map do |job|
        case mass_action
        when :discard
          job.discard_job(DISCARD_MESSAGE)
        when :reschedule
          job.reschedule_job
        when :retry
          job.retry_job
        when :destroy
          job.destroy_job
        end

        job
      rescue GoodJob::Job::ActionForStateMismatchError
        nil
      end.compact

      notice = if processed_jobs.any?
                 "Successfully #{ACTIONS[mass_action]} #{processed_jobs.count} #{'job'.pluralize(processed_jobs.count)}"
               else
                 "No jobs were #{ACTIONS[mass_action]}"
               end

      redirect_back(fallback_location: jobs_path, notice: notice)
    end

    def show
      @job = Job.includes_advisory_locks.find(params[:id])
    end

    def discard
      @job = Job.find(params[:id])
      @job.discard_job(DISCARD_MESSAGE)
      redirect_back(fallback_location: jobs_path, notice: "Job has been discarded")
    end

    def reschedule
      @job = Job.find(params[:id])
      @job.reschedule_job
      redirect_back(fallback_location: jobs_path, notice: "Job has been rescheduled")
    end

    def retry
      @job = Job.find(params[:id])
      @job.retry_job
      redirect_back(fallback_location: jobs_path, notice: "Job has been retried")
    end

    def destroy
      @job = Job.find(params[:id])
      @job.destroy_job
      redirect_to jobs_path, notice: "Job has been destroyed"
    end

    private

    def redirect_on_error(exception)
      alert = case exception
              when GoodJob::Job::AdapterNotGoodJobError
                "ActiveJob Queue Adapter must be GoodJob."
              when GoodJob::Job::ActionForStateMismatchError
                "Job is not in an appropriate state for this action."
              else
                exception.to_s
              end
      redirect_back(fallback_location: jobs_path, alert: alert)
    end
  end
end

app/controllers/good_job/processes_controller.rb
# frozen_string_literal: true
module GoodJob
  class ProcessesController < GoodJob::ApplicationController
    def index
      @processes = GoodJob::Process.active.order(created_at: :desc)
    end
  end
end

app/helpers/good_job/application_helper.rb
# frozen_string_literal: true
module GoodJob
  module ApplicationHelper
    def format_duration(sec)
      return unless sec

      if sec < 1
        t 'good_job.duration.milliseconds', ms: (sec * 1000).floor
      elsif sec < 10
        t 'good_job.duration.less_than_10_seconds', sec: sec.floor
      elsif sec < 60
        t 'good_job.duration.seconds', sec: sec.floor
      elsif sec < 3600
        t 'good_job.duration.minutes', min: (sec / 60).floor, sec: (sec % 60).floor
      else
        t 'good_job.duration.hours', hour: (sec / 3600).floor, min: ((sec % 3600) / 60).floor
      end
    end

    def relative_time(timestamp, **options)
      options = options.reverse_merge({ scope: "good_job.datetime.distance_in_words" })
      text = timestamp.future? ? "in #{time_ago_in_words(timestamp, **options)}" : "#{time_ago_in_words(timestamp, **options)} ago"
      tag.time(text, datetime: timestamp, title: timestamp)
    end

    STATUS_ICONS = {
      discarded: "exclamation",
      succeeded: "check",
      queued: "dash_circle",
      retried: "arrow_clockwise",
      running: "play",
      scheduled: "clock",
    }.freeze

    STATUS_COLOR = {
      discarded: "danger",
      succeeded: "success",
      queued: "secondary",
      retried: "warning",
      running: "primary",
      scheduled: "secondary",
    }.freeze

    def status_badge(status)
      content_tag :span, status_icon(status, class: "text-white") + t(status, scope: 'good_job.status'),
                  class: "badge rounded-pill bg-#{STATUS_COLOR.fetch(status)} d-inline-flex gap-2 ps-1 pe-3 align-items-center"
    end

    def status_icon(status, **options)
      options[:class] ||= "text-#{STATUS_COLOR.fetch(status)}"
      icon = render_icon STATUS_ICONS.fetch(status)
      content_tag :span, icon, **options
    end

    def render_icon(name)
      # workaround to render svg icons without all of the log messages
      partial = lookup_context.find_template("good_job/shared/icons/#{name}", [], true)
      partial.render(self, {})
    end
  end
end

app/views/good_job/batches/_jobs.erb
  <div class="my-3 card" data-gj-poll-replace id="jobs-table">
    <div class="list-group list-group-flush text-nowrap table-jobs" role="table">
      <header class="list-group-item bg-light">
        <div class="row small text-muted text-uppercase align-items-center">
          <div class="col-4">Jobs</div>
          <div class="d-none d-lg-block col-lg-1 text-lg-center">Queue</div>
          <div class="d-none d-lg-block col-lg-1 text-lg-end">Priority</div>
          <div class="d-none d-lg-block col-lg-1 text-lg-end">Attempts</div>
          <div class="col text-end">
            <%= tag.button type: "button", class: "btn btn-sm text-muted", role: "button",
                           data: { bs_toggle: "collapse", bs_target: ".job-params" },
                           aria: { expanded: false, controls: jobs.map { |job| "##{dom_id(job, "params")}" }.join(" ") } do %>
              <%= render_icon "info" %>
              <span class="visually-hidden">Inspect</span>
            <% end %>
          </div>
        </div>
      </header>

      <% if jobs.present? %>
        <% jobs.each do |job| %>
          <div role="row" class="list-group-item list-group-item-action py-3">
            <div class="row align-items-center">
              <div class="col-lg-4">
                <%= tag.code link_to(job.id, job_path(job), class: "small text-muted text-decoration-none") %>
                <%= tag.h5 tag.code(link_to(job.job_class, job_path(job), class: "text-reset text-decoration-none")), class: "text-reset mb-0" %>
              </div>
              <div class="col-4 col-lg-1 text-lg-center">
                <div class="d-lg-none small text-muted mt-1">Queue</div>
                <span class="badge bg-primary bg-opacity-25 text-dark font-monospace"><%= job.queue_name %></span>
              </div>
              <div class="col-4 col-lg-1 text-lg-end">
                <div class="d-lg-none small text-muted mt-1">Priority</div>
                <span class="font-monospace fw-bold"><%= job.priority %></span>
              </div>
              <div class="col-4 col-lg-1 text-lg-end">
                <div class="d-lg-none small text-muted mt-1">Attempts</div>
                <% if job.executions_count > 0 && job.status != :finished %>
                  <%= tag.span job.executions_count, class: "badge rounded-pill bg-danger", data: {
                    bs_toggle: "popover",
                    bs_trigger: "hover focus click",
                    bs_placement: "bottom",
                    bs_content: job.recent_error
                  } %>
                <% else %>
                  <span class="badge bg-secondary bg-opacity-50 rounded-pill"><%= job.executions_count %></span>
                <% end %>
              </div>
              <div class="mt-3 mt-lg-0 col d-flex gap-3 align-items-center justify-content-end">
                <%= tag.span relative_time(job.last_status_at), class: "small" %>
                <%= status_badge job.status %>

                <div class="dropdown float-end">
                  <button class="d-flex align-items-center btn btn-sm" type="button" id="<%= dom_id(job, :actions) %>" data-bs-toggle="dropdown" aria-expanded="false">
                    <%= render "good_job/shared/icons/dots" %>
                    <span class="visually-hidden">Actions</span>
                  </button>
                  <ul class="dropdown-menu shadow" aria-labelledby="<%= dom_id(job, :actions) %>">
                    <li>
                      <% job_reschedulable = job.status.in? [:scheduled, :retried, :queued] %>
                      <%= link_to reschedule_job_path(job.id), method: :put, class: "dropdown-item #{'disabled' unless job_reschedulable}", title: "Reschedule job", data: { confirm: "Confirm reschedule", disable: true } do %>
                        <%= render "good_job/shared/icons/skip_forward" %>
                        Reschedule
                      <% end %>
                    </li>
                    <li>
                      <% job_discardable = job.status.in? [:scheduled, :retried, :queued] %>
                      <%= link_to discard_job_path(job.id), method: :put, class: "dropdown-item #{'disabled' unless job_discardable}", title: "Discard job", data: { confirm: "Confirm discard", disable: true } do %>
                        <%= render "good_job/shared/icons/stop" %>
                        Discard
                      <% end %>
                    </li>
                    <li>
                      <%= link_to retry_job_path(job.id), method: :put, class: "dropdown-item #{'disabled' unless job.status == :discarded}", title: "Retry job", data: { confirm: "Confirm retry", disable: true } do %>
                        <%= render "good_job/shared/icons/arrow_clockwise" %>
                        Retry
                      <% end %>
                    </li>
                    <li>
                      <%= link_to job_path(job.id), method: :delete, class: "dropdown-item #{'disabled' unless job.status.in? [:discarded, :finished]}", title: "Destroy job", data: { confirm: "Confirm destroy", disable: true } do %>
                        <%= render_icon "trash" %>
                        Destroy
                      <% end %>
                    </li>

                    <li>
                      <%= link_to "##{dom_id(job, 'params')}",
                                  class: "dropdown-item",
                                  data: { bs_toggle: "collapse" },
                                  aria: { expanded: false, controls: dom_id(job, "params") } do %>
                        <%= render_icon "info" %>
                        Inspect
                      <% end %>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <%= tag.div id: dom_id(job, "params"), class: "job-params list-group-item collapse small bg-dark text-light" do %>
            <%= tag.pre JSON.pretty_generate(job.display_serialized_params) %>
          <% end %>
        <% end %>
      <% else %>
        <div class="list-group-item py-4 text-center text-muted">
          No jobs found.
        </div>
      <% end %>
    </div>
  </div>

app/views/good_job/batches/_table.erb
  <div class="my-3 card" data-gj-poll-replace id="batches-table">
    <div class="list-group list-group-flush text-nowrap table-batches" role="table">
      <header class="list-group-item bg-light">
        <div class="row small text-muted text-uppercase align-items-center">
          <div class="col-4">Name</div>
          <div class="col-lg-1 d-none d-lg-block">Created</div>
          <div class="col-lg-1 d-none d-lg-block">Enqueued</div>
          <div class="col-lg-1 d-none d-lg-block">Discarded</div>
          <div class="col-lg-1 d-none d-lg-block">Finished</div>
          <div class="col-lg-1 d-none d-lg-block">Jobs</div>
          <div class="col text-end">
            <%= tag.button type: "button", class: "btn btn-sm text-muted", role: "button",
                           data: { bs_toggle: "collapse", bs_target: ".batch-properties" },
                           aria: { expanded: false, controls: batches.map { |batch| "##{dom_id(batch, "params")}" }.join(" ") } do %>
              <%= render_icon "info" %>
              <span class="visually-hidden">Inspect</span>
            <% end %>
          </div>
        </div>
      </header>

      <% if batches.present? %>
        <% batches.each do |batch| %>
          <div id="<%= dom_id(batch) %>" class="list-group-item py-3" role="row">
            <div class="row align-items-center">
              <div class="col-12 col-lg-4">
                <%= link_to batch_path(batch), class: "text-decoration-none" do %>
                  <code class="small text-muted">
                    <%= batch.id %>
                  </code>
                  <h5 class=""><code><%= batch.on_finish %></code></h5>
                  <div class="text-muted"><%= batch.description %></div>
                <% end %>
              </div>
              <div class="col-6 col-lg-1 text-wrap">
                <div class="d-lg-none small text-muted mt-1">Created at</div>
                <%= relative_time(batch.created_at) %>
              </div>
              <div class="col-6 col-lg-1 text-wrap">
                <% if batch.enqueued_at %>
                  <div class="d-lg-none small text-muted mt-1">Enqueued at</div>
                  <%= relative_time(batch.enqueued_at) %>
                <% end %>
              </div>
              <div class="col-6 col-lg-1 text-wrap">
                <% if batch.discarded_at %>
                  <div class="d-lg-none small text-muted mt-1">Discarded at</div>
                  <%= relative_time(batch.discarded_at) %>
                <% end %>
              </div>
              <div class="col-6 col-lg-1 text-wrap">
                <% if batch.finished_at %>
                  <div class="d-lg-none small text-muted mt-1">Finished at</div>
                  <%= relative_time(batch.finished_at) %>
                <% end %>
              </div>
              <div class="col-6 col-lg-1">
                <div class="d-lg-none small text-muted mt-1">Jobs</div>
                <%= batch.jobs.count %>
              </div>
              <div class="col text-end">
                <%= tag.button type: "button", class: "btn btn-sm text-muted", role: "button",
                               title: "Inspect",
                               data: { bs_toggle: "collapse", bs_target: "##{dom_id(batch, 'properties')}" },
                               aria: { expanded: false, controls: dom_id(batch, "state") } do %>
                  <%= render_icon "info" %>
                  <span class="visually-hidden">Inspect</span>
                <% end %>
              </div>
            </div>
          </div>
          <%= tag.div id: dom_id(batch, "properties"), class: "batch-properties list-group-item collapse small bg-dark text-light" do %>
            <%= tag.pre JSON.pretty_generate(batch.properties) %>
          <% end %>
        <% end %>
      <% else %>
        <div class="list-group-item py-4 text-center text-muted">
          No batches found.
        </div>
      <% end %>
    </div>
  </div>

app/views/good_job/batches/index.html.erb
<div class="border-bottom">
  <h2 class="pt-3 pb-2">Batches</h2>
</div>

<% if GoodJob::BatchRecord.migrated? %>
  <%= render 'good_job/batches/table', batches: @filter.records, filter: @filter %>
  <% if @filter.records.present? %>
    <nav aria-label="Batch pagination" class="mt-3">
      <ul class="pagination">
        <li class="page-item">
          <%= link_to(@filter.to_params(after_created_at: @filter.last.created_at, after_id: @filter.last.id), class: "page-link") do %>
            Older batches <span aria-hidden="true">&raquo;</span>
          <% end %>
        </li>
      </ul>
    </nav>
  <% end %>
<% else %>
  <h3 class="text-center my-5">GoodJob has pending database migrations.</h3>
<% end %>

app/views/good_job/batches/show.html.erb
<div class="border-bottom py-2 mb-3">
  <div class="pt-2">
    <div class="row align-items-center">
      <div class="col">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb small mb-0">
            <li class="breadcrumb-item"><%= link_to "Batches", batches_path %></li>
            <li class="breadcrumb-item active" aria-current="page"><%= tag.code @batch.id, class: "text-muted" %></li>
          </ol>
          <h2 class="h5 mt-2"><%= @batch.description %></h2>
        </nav>
      </div>
    </div>
  </div>
</div>

<div class="my-4">
  <h5>Attributes</h5>
  <div class="bg-dark text-light p-3 rounded">
    <%= tag.pre JSON.pretty_generate @batch.display_attributes, class: 'text-wrap text-break' %>
  </div>
</div>

<div class="my-4">
  <h5>Callback Jobs</h5>
  <%= render 'jobs', jobs: @batch.callback_jobs.reverse %>
</div>

<div class="my-4">
  <h5>Batched Jobs</h5>
  <%= render 'jobs', jobs: @batch.jobs.reverse %>
</div>