config/routes.rb
# frozen_string_literal: true
GoodJob::Engine.routes.draw do
  root to: redirect(path: 'jobs')

  resources :jobs, only: %i[index show destroy] do
    collection do
      get :mass_update, to: redirect(path: 'jobs')
      put :mass_update
    end

    member do
      put :discard
      put :reschedule
      put :retry
    end
  end

  resources :batches, only: %i[index show]

  resources :cron_entries, only: %i[index show], param: :cron_key do
    member do
      post :enqueue
      put :enable
      put :disable
    end
  end

  resources :processes, only: %i[index]

  scope :frontend, controller: :frontends do
    get "modules/:name", action: :module, as: :frontend_module, constraints: { format: 'js' }
    get "static/:name", action: :static, as: :frontend_static, constraints: { format: %w[css js] }
  end
end

app/models/concerns/good_job/filterable.rb
# frozen_string_literal: true
module GoodJob
  # Shared methods for filtering Execution/Job records from the +good_jobs+ table.
  module Filterable
    extend ActiveSupport::Concern

    included do
      # Get records in display order with optional keyset pagination.
      # @!method display_all(after_scheduled_at: nil, after_id: nil)
      # @!scope class
      # @param after_scheduled_at [DateTime, String, nil]
      #   Display records scheduled after this time for keyset pagination
      # @param after_id [Numeric, String, nil]
      #   Display records after this ID for keyset pagination
      # @return [ActiveRecord::Relation]
      scope :display_all, (lambda do |after_scheduled_at: nil, after_id: nil|
        query = order(Arel.sql('COALESCE(scheduled_at, created_at) DESC, id DESC'))
        if after_scheduled_at.present? && after_id.present?
          query = query.where(Arel.sql('(COALESCE(scheduled_at, created_at), id) < (:after_scheduled_at, :after_id)'), after_scheduled_at: after_scheduled_at, after_id: after_id)
        elsif after_scheduled_at.present?
          query = query.where(Arel.sql('(COALESCE(scheduled_at, created_at)) < (:after_scheduled_at)'), after_scheduled_at: after_scheduled_at)
        end
        query
      end)

      # Search records by text query.
      # @!method search_text(query)
      # @!scope class
      # @param query [String]
      #   Search Query
      # @return [ActiveRecord::Relation]
      scope :search_text, (lambda do |query|
        query = query.to_s.strip
        next if query.blank?

        tsvector = "(to_tsvector('english', serialized_params) || to_tsvector('english', id::text) || to_tsvector('english', COALESCE(error, '')::text))"
        to_tsquery_function = database_supports_websearch_to_tsquery? ? 'websearch_to_tsquery' : 'plainto_tsquery'
        where("#{tsvector} @@ #{to_tsquery_function}(?)", query)
          .order(sanitize_sql_for_order([Arel.sql("ts_rank(#{tsvector}, #{to_tsquery_function}(?))"), query]) => 'DESC')
      end)
    end

    class_methods do
      def database_supports_websearch_to_tsquery?
        return @_database_supports_websearch_to_tsquery if defined?(@_database_supports_websearch_to_tsquery)

        @_database_supports_websearch_to_tsquery = connection.postgresql_version >= 110000
      end
    end
  end
end

app/models/good_job/batch_record.rb
# frozen_string_literal: true

module GoodJob
  class BatchRecord < BaseRecord
    include Lockable

    self.table_name = 'good_job_batches'

    has_many :jobs, class_name: 'GoodJob::Job', inverse_of: :batch, foreign_key: :batch_id, dependent: nil
    has_many :executions, class_name: 'GoodJob::Execution', foreign_key: :batch_id, inverse_of: :batch, dependent: nil
    has_many :callback_jobs, class_name: 'GoodJob::Job', foreign_key: :batch_callback_id, dependent: nil # rubocop:disable Rails/InverseOf

    scope :finished, -> { where.not(finished_at: nil) }
    scope :discarded, -> { where.not(discarded_at: nil) }
    scope :not_discarded, -> { where(discarded_at: nil) }
    scope :succeeded, -> { finished.not_discarded }

    alias_attribute :enqueued?, :enqueued_at
    alias_attribute :discarded?, :discarded_at
    alias_attribute :finished?, :finished_at

    scope :display_all, (lambda do |after_created_at: nil, after_id: nil|
      query = order(created_at: :desc, id: :desc)
      if after_created_at.present? && after_id.present?
        query = query.where(Arel.sql('(created_at, id) < (:after_created_at, :after_id)'), after_created_at: after_created_at, after_id: after_id)
      elsif after_created_at.present?
        query = query.where(Arel.sql('(after_created_at) < (:after_created_at)'), after_created_at: after_created_at)
      end
      query
    end)

    # Whether the batch has finished and no jobs were discarded
    # @return [Boolean]
    def succeeded?
      !discarded? && finished?
    end

    def to_batch
      Batch.new(_record: self)
    end

    def display_attributes
      attributes.except('serialized_properties').merge(properties: properties)
    end

    def _continue_discard_or_finish(execution = nil, lock: true)
      execution_discarded = execution && execution.error.present? && execution.retried_good_job_id.nil?
      take_advisory_lock(lock) do
        Batch.within_thread(batch_id: nil, batch_callback_id: id) do
          reload
          if execution_discarded && !discarded_at
            update(discarded_at: Time.current)
            on_discard.constantize.set(priority: callback_priority, queue: callback_queue_name).perform_later(to_batch, { event: :discard }) if on_discard.present?
          end

          if enqueued_at && !finished_at && jobs.where(finished_at: nil).count.zero?
            update(finished_at: Time.current)
            on_success.constantize.set(priority: callback_priority, queue: callback_queue_name).perform_later(to_batch, { event: :success }) if !discarded_at && on_success.present?
            on_finish.constantize.set(priority: callback_priority, queue: callback_queue_name).perform_later(to_batch, { event: :finish }) if on_finish.present?
          end
        end
      end
    end

    class PropertySerializer
      def self.dump(value)
        ActiveJob::Arguments.serialize([value]).first
      end

      def self.load(value)
        ActiveJob::Arguments.deserialize([value]).first
      end
    end

    if Rails.gem_version < Gem::Version.new('6.1.0.alpha')
      # serialize does not yet take a default value, must set via Attributes API
      attribute :serialized_properties, :json, default: -> { {} }
      serialize :serialized_properties, PropertySerializer
    elsif Rails.gem_version < Gem::Version.new('7.1.0.alpha')
      serialize :serialized_properties, PropertySerializer, default: -> { {} }
    else
      serialize :serialized_properties, coder: PropertySerializer, default: -> { {} }
    end
    alias_attribute :properties, :serialized_properties

    def properties=(value)
      raise ArgumentError, "Properties must be a Hash" unless value.is_a?(Hash)

      self.serialized_properties = value
    end

    private

    def take_advisory_lock(value, &block)
      if value
        with_advisory_lock(function: "pg_advisory_lock", &block)
      else
        yield
      end
    end
  end
end

app/controllers/good_job/application_controller.rb
# frozen_string_literal: true
module GoodJob
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    around_action :switch_locale

    content_security_policy do |policy|
      policy.default_src(:none) if policy.default_src(*policy.default_src).blank?
      policy.connect_src(:self) if policy.connect_src(*policy.connect_src).blank?
      policy.base_uri(:none) if policy.base_uri(*policy.base_uri).blank?
      policy.font_src(:self) if policy.font_src(*policy.font_src).blank?
      policy.img_src(:self, :data) if policy.img_src(*policy.img_src).blank?
      policy.object_src(:none) if policy.object_src(*policy.object_src).blank?
      policy.script_src(:self) if policy.script_src(*policy.script_src).blank?
      policy.style_src(:self) if policy.style_src(*policy.style_src).blank?
      policy.form_action(:self) if policy.form_action(*policy.form_action).blank?
      policy.frame_ancestors(:none) if policy.frame_ancestors(*policy.frame_ancestors).blank?
    end

    before_action do
      next if request.content_security_policy_nonce_generator

      request.content_security_policy_nonce_generator = ->(_request) { SecureRandom.base64(16) }
    end

    private

    def default_url_options(options = {})
      { locale: I18n.locale }.merge(options)
    end

    def switch_locale(&action)
      I18n.with_locale(current_locale, &action)
    end

    def current_locale
      if params[:locale]
        params[:locale]
      elsif good_job_available_locales.exclude?(I18n.default_locale) && I18n.available_locales.include?(:en)
        :en
      else
        I18n.default_locale
      end
    end

    def good_job_available_locales
      @_good_job_available_locales ||= GoodJob::Engine.root.join("config/locales").glob("*.yml").map { |path| File.basename(path, ".yml").to_sym }.uniq
    end
  end
end

app/controllers/good_job/batches_controller.rb
# frozen_string_literal: true
module GoodJob
  class BatchesController < GoodJob::ApplicationController
    def index
      @filter = BatchesFilter.new(params)
    end

    def show
      @batch = GoodJob::BatchRecord.find(params[:id])
    end
  end
end

app/controllers/good_job/cron_entries_controller.rb
# frozen_string_literal: true
module GoodJob
  class CronEntriesController < GoodJob::ApplicationController
    before_action :check_settings_migration!, only: [:enable, :disable]

    def index
      @cron_entries = CronEntry.all
    end

    def show
      @cron_entry = CronEntry.find(params[:cron_key])
      @jobs_filter = JobsFilter.new(params, @cron_entry.jobs)
    end

    def enqueue
      @cron_entry = CronEntry.find(params[:cron_key])
      @cron_entry.enqueue(Time.current)
      redirect_back(fallback_location: cron_entries_path, notice: "Cron entry has been enqueued.")
    end

    def enable
      @cron_entry = CronEntry.find(params[:cron_key])
      @cron_entry.enable
      redirect_back(fallback_location: cron_entries_path, notice: "Cron entry has been enabled.")
    end

    def disable
      @cron_entry = CronEntry.find(params[:cron_key])
      @cron_entry.disable
      redirect_back(fallback_location: cron_entries_path, notice: "Cron entry has been disabled.")
    end

    private

    def check_settings_migration!
      redirect_back(fallback_location: cron_entries_path, alert: "Requires pending GoodJob database migration.") unless GoodJob::Setting.migrated?
    end
  end
end

app/controllers/good_job/frontends_controller.rb
# frozen_string_literal: true
module GoodJob
  class FrontendsController < ActionController::Base # rubocop:disable Rails/ApplicationController
    skip_after_action :verify_same_origin_request, raise: false

    STATIC_ASSETS = {
      css: {
        bootstrap: GoodJob::Engine.root.join("app", "frontend", "good_job", "vendor", "bootstrap", "bootstrap.min.css"),
        style: GoodJob::Engine.root.join("app", "frontend", "good_job", "style.css"),
      },
      js: {
        bootstrap: GoodJob::Engine.root.join("app", "frontend", "good_job", "vendor", "bootstrap", "bootstrap.bundle.min.js"),
        chartjs: GoodJob::Engine.root.join("app", "frontend", "good_job", "vendor", "chartjs", "chart.min.js"),
        es_module_shims: GoodJob::Engine.root.join("app", "frontend", "good_job", "vendor", "es_module_shims.js"),
        rails_ujs: GoodJob::Engine.root.join("app", "frontend", "good_job", "vendor", "rails_ujs.js"),
      },
    }.freeze

    MODULE_OVERRIDES = {
      application: GoodJob::Engine.root.join("app", "frontend", "good_job", "application.js"),
      stimulus: GoodJob::Engine.root.join("app", "frontend", "good_job", "vendor", "stimulus.js"),
    }.freeze

    def self.js_modules
      @_js_modules ||= GoodJob::Engine.root.join("app", "frontend", "good_job", "modules").children.select(&:file?).each_with_object({}) do |file, modules|
        key = File.basename(file.basename.to_s, ".js").to_sym
        modules[key] = file
      end.merge(MODULE_OVERRIDES)
    end

    before_action do
      expires_in 1.year, public: true
    end

    def static
      render file: STATIC_ASSETS.dig(params[:format].to_sym, params[:name].to_sym) || raise(ActionController::RoutingError, 'Not Found')
    end

    def module
      raise(ActionController::RoutingError, 'Not Found') if params[:format] != "js"

      render file: self.class.js_modules[params[:name].to_sym] || raise(ActionController::RoutingError, 'Not Found')
    end
  end
end

app/controllers/good_job/jobs_controller.rb
# frozen_string_literal: true
module GoodJob
  class JobsController < GoodJob::ApplicationController
    DISCARD_MESSAGE = "Discarded through dashboard"

    ACTIONS = {
      discard: "discarded",
      reschedule: "rescheduled",
      retry: "retried",
      destroy: "destroyed",
    }.freeze

    rescue_from GoodJob::Job::AdapterNotGoodJobError,
                GoodJob::Job::ActionForStateMismatchError,
                with: :redirect_on_error

    def index
      @filter = JobsFilter.new(params)
    end

    def mass_update
      mass_action = params.fetch(:mass_action, "").to_sym
      raise ActionController::BadRequest, "#{mass_action} is not a valid mass action" unless mass_action.in?(ACTIONS.keys)

      jobs = if params[:all_job_ids]
               JobsFilter.new(params).filtered_query
             else
               job_ids = params.fetch(:job_ids, [])
               Job.where(active_job_id: job_ids)
             end

      processed_jobs = jobs.map do |job|
        case mass_action
        when :discard
          job.discard_job(DISCARD_MESSAGE)
        when :reschedule
          job.reschedule_job
        when :retry
          job.retry_job
        when :destroy
          job.destroy_job
        end

        job
      rescue GoodJob::Job::ActionForStateMismatchError
        nil
      end.compact

      notice = if processed_jobs.any?
                 "Successfully #{ACTIONS[mass_action]} #{processed_jobs.count} #{'job'.pluralize(processed_jobs.count)}"
               else
                 "No jobs were #{ACTIONS[mass_action]}"
               end

      redirect_back(fallback_location: jobs_path, notice: notice)
    end

    def show
      @job = Job.includes_advisory_locks.find(params[:id])
    end

    def discard
      @job = Job.find(params[:id])
      @job.discard_job(DISCARD_MESSAGE)
      redirect_back(fallback_location: jobs_path, notice: "Job has been discarded")
    end

    def reschedule
      @job = Job.find(params[:id])
      @job.reschedule_job
      redirect_back(fallback_location: jobs_path, notice: "Job has been rescheduled")
    end

    def retry
      @job = Job.find(params[:id])
      @job.retry_job
      redirect_back(fallback_location: jobs_path, notice: "Job has been retried")
    end

    def destroy
      @job = Job.find(params[:id])
      @job.destroy_job
      redirect_to jobs_path, notice: "Job has been destroyed"
    end

    private

    def redirect_on_error(exception)
      alert = case exception
              when GoodJob::Job::AdapterNotGoodJobError
                "ActiveJob Queue Adapter must be GoodJob."
              when GoodJob::Job::ActionForStateMismatchError
                "Job is not in an appropriate state for this action."
              else
                exception.to_s
              end
      redirect_back(fallback_location: jobs_path, alert: alert)
    end
  end
end

app/controllers/good_job/processes_controller.rb
# frozen_string_literal: true
module GoodJob
  class ProcessesController < GoodJob::ApplicationController
    def index
      @processes = GoodJob::Process.active.order(created_at: :desc)
    end
  end
end

app/helpers/good_job/application_helper.rb
# frozen_string_literal: true
module GoodJob
  module ApplicationHelper
    def format_duration(sec)
      return unless sec

      if sec < 1
        t 'good_job.duration.milliseconds', ms: (sec * 1000).floor
      elsif sec < 10
        t 'good_job.duration.less_than_10_seconds', sec: sec.floor
      elsif sec < 60
        t 'good_job.duration.seconds', sec: sec.floor
      elsif sec < 3600
        t 'good_job.duration.minutes', min: (sec / 60).floor, sec: (sec % 60).floor
      else
        t 'good_job.duration.hours', hour: (sec / 3600).floor, min: ((sec % 3600) / 60).floor
      end
    end

    def relative_time(timestamp, **options)
      options = options.reverse_merge({ scope: "good_job.datetime.distance_in_words" })
      text = timestamp.future? ? "in #{time_ago_in_words(timestamp, **options)}" : "#{time_ago_in_words(timestamp, **options)} ago"
      tag.time(text, datetime: timestamp, title: timestamp)
    end

    STATUS_ICONS = {
      discarded: "exclamation",
      succeeded: "check",
      queued: "dash_circle",
      retried: "arrow_clockwise",
      running: "play",
      scheduled: "clock",
    }.freeze

    STATUS_COLOR = {
      discarded: "danger",
      succeeded: "success",
      queued: "secondary",
      retried: "warning",
      running: "primary",
      scheduled: "secondary",
    }.freeze

    def status_badge(status)
      content_tag :span, status_icon(status, class: "text-white") + t(status, scope: 'good_job.status'),
                  class: "badge rounded-pill bg-#{STATUS_COLOR.fetch(status)} d-inline-flex gap-2 ps-1 pe-3 align-items-center"
    end

    def status_icon(status, **options)
      options[:class] ||= "text-#{STATUS_COLOR.fetch(status)}"
      icon = render_icon STATUS_ICONS.fetch(status)
      content_tag :span, icon, **options
    end

    def render_icon(name)
      # workaround to render svg icons without all of the log messages
      partial = lookup_context.find_template("good_job/shared/icons/#{name}", [], true)
      partial.render(self, {})
    end
  end
end

app/views/good_job/jobs/_executions.erb
<h5>Executions</h5>
<div class="card mb-4" data-live-poll-region="executions-table">
  <div class="list-group list-group-flush">
    <% executions.each do |execution| %>
      <%= tag.div id: dom_id(execution), class: "list-group-item py-3" do %>
        <div class="row align-items-center text-nowrap">
          <div class="col-md-5 d-flex gap-2">
            <%= tag.span execution.number, class: "badge bg-secondary bg-opacity-50 rounded-pill" %>
            <%= tag.code link_to(execution.id, "##{dom_id(execution)}", class: "text-muted text-decoration-none small") %>
          </div>
          <div class="col-md-2 small">
            <% if execution.queue_latency %>
              <%= format_duration execution.queue_latency %> <span class="text-muted">in queue</span>
            <% end %>
          </div>
          <div class="col-md-2 small">
            <% if execution.runtime_latency %>
              <%= format_duration execution.runtime_latency %> <span class="text-muted">runtime</span>
            <% end %>
          </div>
          <div class="col">
            <div class="d-flex gap-3 align-items-center justify-content-end">
              <%= tag.span relative_time(execution.last_status_at, include_seconds: true), class: "small" %>
              <%= status_badge execution.status %>
            
              <%= tag.button type: "button", class: "btn btn-sm text-muted", role: "button",
                title: "Inspect",
                data: { bs_toggle: "collapse", bs_target: "##{dom_id(execution, 'params')}" },
                aria: { expanded: false, controls: dom_id(execution, "params") } do %>
                <%= render_icon "info" %>
                <span class="visually-hidden">Inspect</span>
              <% end %>
            </div>
          </div>
        </div>
        <% if execution.error %>
          <div class="mt-3 small">
            <strong class="small">Error:</strong>
            <code class="text-wrap text-break m-0 text-black"><%= execution.error %></code>
          </div>
        <% end %>
      <% end %>
      <%= tag.div id: dom_id(execution, "params"), class: "list-group-item collapse small bg-dark text-light" do %>
        <%= tag.pre JSON.pretty_generate(execution.display_serialized_params) %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/good_job/jobs/_table.erb
<%= form_with(url: mass_update_jobs_path(filter.to_params), method: :put, local: true, data: { "checkbox-toggle": "job_ids" }) do |form| %>
<div class="my-3 card" data-gj-poll-replace id="jobs-table">
  <div class="list-group list-group-flush text-nowrap table-jobs" role="table">
    <header class="list-group-item bg-light">
      <div class="row small text-muted text-uppercase align-items-center">
        <div class="col-lg-4 d-flex gap-2 flex-wrap">
          <%= label_tag('toggle_job_ids', "Toggle all jobs", class: "visually-hidden") %>
          <%= check_box_tag('toggle_job_ids', "1", false, data: { "checkbox-toggle-all": "job_ids" }) %>

          <%= form.button type: 'submit', name: 'mass_action', value: 'reschedule', class: 'ms-1 btn btn-sm btn-outline-secondary', title: "Reschedule all", data: { confirm: "Are you sure you want to reschedule the selected jobs?", disable: true } do %>
            <span class="me-1"><%= render_icon "skip_forward" %></span> Reschedule
          <% end %>

          <%= form.button type: 'submit', name: 'mass_action', value: 'retry', class: 'btn btn-sm btn-outline-secondary', title: "Retry all", data: { confirm: "Are you sure you want to retry the selected jobs?", disable: true } do %>
            <span class="me-1"><%= render_icon "arrow_clockwise" %></span> Retry
          <% end %>

          <div class="btn-group" role="group">
            <%= form.button type: 'submit', name: 'mass_action', value: 'discard', class: 'btn btn-sm btn-outline-secondary', title: "Discard all", data: { confirm: "Are you usure you want to discard the selected jobs?", disable: true } do %>
              <span class="me-1"><%= render_icon "stop" %></span> Discard
            <% end %>
            <button id="destroy-dropdown-toggle" type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
              <span class="visually-hidden">Toggle Actions</span>
            </button>
            <div class="dropdown-menu" aria-labelledby="destroy-dropdown-toggle">
              <li>
                <%= form.button type: 'submit', name: 'mass_action', value: 'destroy', class: 'btn', title: "Destroy all", data: { confirm: "Are you sure you want to destroy the selected jobs?", disable: true } do %>
                  <span class="me-1"><%= render_icon "trash" %></span> Destroy
                <% end %>
              </li>
            </div>
          </div>

        </div>
        <div class="d-none d-lg-block col-lg-1 text-lg-center">Queue</div>
        <div class="d-none d-lg-block col-lg-1 text-lg-end">Priority</div>
        <div class="d-none d-lg-block col-lg-1 text-lg-end">Attempts</div>
        <div class="col text-end">
          <%= tag.button type: "button", class: "btn btn-sm text-muted", role: "button",
                  data: { bs_toggle: "collapse", bs_target: ".job-params" },
                  aria: { expanded: false, controls: jobs.map { |job| "##{dom_id(job, "params")}" }.join(" ") } do %>
              <%= render_icon "info" %>
              <span class="visually-hidden">Inspect</span>
          <% end %>
        </div>
      </div>
    </header>
    <label role="row" class="list-group-item list-group-item-warning list-group-item-action py-3 d-none" data-checkbox-toggle-show="job_ids">
      <div class="row">
        <div class="col-auto">
          <%= check_box_tag "all_job_ids", 1, false, disabled: true, data: { "checkbox-toggle-show": "job_ids"} %>
        </div>
        <div class="col-auto">
          Apply to all <%= filter.filtered_count %> <%= "job".pluralize(filter.filtered_count) %>.
        </div>
      </div>
    </label>

    <% if jobs.present? %>
      <% jobs.each do |job| %>
        <%= label_tag dom_id(job, :checkbox), id: dom_id(job), role: "row", class: "list-group-item list-group-item-action py-3" do %>
          <div class="row align-items-center">
            <div class="col-lg-4 d-flex">
              <%= check_box_tag 'job_ids[]', job.id, false, id: dom_id(job, :checkbox), data: { "checkbox-toggle-each": "job_ids" } %>
              <div class="ms-2">
                <%= tag.code link_to(job.id, job_path(job), class: "small text-muted text-decoration-none") %>
                <%= tag.h5 tag.code(link_to(job.job_class, job_path(job), class: "text-reset text-decoration-none")), class: "text-reset mb-0" %>
              </div>
            </div>
            <div class="col-4 col-lg-1 text-lg-center">
              <div class="d-lg-none small text-muted mt-1">Queue</div>
              <span class="badge bg-primary bg-opacity-25 text-dark font-monospace"><%= job.queue_name %></span>
            </div>
            <div class="col-4 col-lg-1 text-lg-end">
              <div class="d-lg-none small text-muted mt-1">Priority</div>
              <%= job.priority %>
            </div>
            <div class="col-4 col-lg-1 text-lg-end">
              <div class="d-lg-none small text-muted mt-1">Attempts</div>
              <% if job.executions_count > 0 && job.status != :succeeded %>
                <%= tag.span job.executions_count, class: "badge rounded-pill bg-danger", data: {
                      bs_toggle: "popover",
                      bs_trigger: "hover focus click",
                      bs_placement: "bottom",
                      bs_content: job.display_error,
                } %>
              <% else %>
                <span class="badge bg-secondary bg-opacity-50 rounded-pill"><%= job.executions_count %></span>
              <% end %>
            </div>
            <div class="mt-3 mt-lg-0 col">
              <div class="d-flex gap-3 align-items-center justify-content-end">
                <%= tag.span relative_time(job.last_status_at), class: "small" %>
                <%= status_badge job.status %>

                <div class="dropdown float-end">
                  <button class="d-flex align-items-center btn btn-sm" type="button" id="<%= dom_id(job, :actions) %>" data-bs-toggle="dropdown" aria-expanded="false">
                    <%= render "good_job/shared/icons/dots" %>
                    <span class="visually-hidden">Actions</span>
                  </button>
                  <ul class="dropdown-menu shadow" aria-labelledby="<%= dom_id(job, :actions) %>">
                    <li>
                      <% job_reschedulable = job.status.in? [:scheduled, :retried, :queued] %>
                      <%= link_to reschedule_job_path(job.id), method: :put, class: "dropdown-item #{'disabled' unless job_reschedulable}", title: "Reschedule job", data: { confirm: "Confirm reschedule", disable: true } do %>
                        <%= render "good_job/shared/icons/skip_forward" %>
                        Reschedule
                      <% end %>
                    </li>
                    <li>
                      <% job_discardable = job.status.in? [:scheduled, :retried, :queued] %>
                      <%= link_to discard_job_path(job.id), method: :put, class: "dropdown-item #{'disabled' unless job_discardable}", title: "Discard job", data: { confirm: "Confirm discard", disable: true } do %>
                        <%= render "good_job/shared/icons/stop" %>
                        Discard
                      <% end %>
                    </li>
                    <li>
                      <%= link_to retry_job_path(job.id), method: :put, class: "dropdown-item #{'disabled' unless job.status == :discarded}", title: "Retry job", data: { confirm: "Confirm retry", disable: true } do %>
                        <%= render "good_job/shared/icons/arrow_clockwise" %>
                        Retry
                      <% end %>
                    </li>
                    <li>
                      <%= link_to job_path(job.id), method: :delete, class: "dropdown-item #{'disabled' unless job.status.in? [:discarded, :succeeded]}", title: "Destroy job", data: { confirm: "Confirm destroy", disable: true } do %>
                        <%= render_icon "trash" %>
                        Destroy
                      <% end %>
                    </li>

                    <li>
                      <%= link_to "##{dom_id(job, 'params')}",
                        class: "dropdown-item",
                        data: { bs_toggle: "collapse" },
                        aria: { expanded: false, controls: dom_id(job, "params") } do %>
                        <%= render_icon "info" %>
                        Inspect
                      <% end %>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <%= tag.div id: dom_id(job, "params"), class: "job-params list-group-item collapse small bg-dark text-light" do %>
          <%= tag.pre JSON.pretty_generate(job.display_serialized_params) %>
        <% end %>
      <% end %>
    <% else %>
      <div class="list-group-item py-4 text-center text-muted">
        No jobs found.
      </div>
    <% end %>
  </div>
</div>
<% end %>